### ISSUE TITLE
Key is stored in legacy trusted.gpg keyring

### ISSUE THREAD

**Issue by tomasnorre** [ddev/github-action-setup-ddev#27]
When running the Crawler Acceptance Tests (1), which uses DDEV GitHub Action, I get follow error

```shell
W: https://apt.fury.io/drud/dists/*/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: GPG error: http://ppa.launchpad.net/ondrej/php/ubuntu jammy InRelease: The following signatures were invalid: ERRSIG 4F4EA0AAE5267A6C
E: The repository 'http://ppa.launchpad.net/ondrej/php/ubuntu jammy InRelease' is not signed.
```

It's related to https://github.com/ddev/github-action-setup-ddev/blob/main/lib/main.js#L62 
I should be something like this instead (2), but not the right person to update it.

Update: 
Reading the Error again, it looks more like a two fix:

Update 2: 
I have split the ppa.launchpad.net/ondrej/php/ubuntu error in a separate issues, as they are not related.

1: for the fury.io which is "only" warning
2: a fix for the Ondrej/php repo

1) https://github.com/tomasnorre/crawler/actions/runs/8892439954/job/24416494672
2) https://gemfury.com/help/apt-repository#apt-setup

**Comment by rfay** [comment]
There are so many things wrong there. "drud" is long obsolete, and the installation location has moved. https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/#__tabbed_1_2

**Comment by tomasnorre** [comment]
Yeah, I have seen that, but isn't sure how it should be.

**Comment by tomasnorre** [comment]
Will see if I can provide a PR, but cannot promise anything.
