### ISSUE TITLE
ddev must accept the GitHub Marketplace Developer Agreement. Contact an org admin to accept it.

### ISSUE THREAD

**Issue by davereid** [ddev/github-action-setup-ddev#8]
![image](https://user-images.githubusercontent.com/62967/234362601-e7319460-95cb-4793-a9e7-953e35e5e35d.png)

**Comment by davereid** [comment]
cc @rfay

**Comment by rfay** [comment]
Done. You're going to have a little unanticipated trouble now with the name though:

<img width="935" alt="image" src="https://user-images.githubusercontent.com/112444/234383688-dee9cf77-e2b3-452d-8ae1-b135d224b546.png">

**Comment by rfay** [comment]
We can rename the repo if necessary. I hate for it to be too confusing with the older one.

**Comment by davereid** [comment]
I don't think it's the repo that needs to be renamed, I proposed adding a "(deprecated)" suffix to the existing action name in https://github.com/jonaseberle/github-action-setup-ddev/pull/36.
